server_port: 9000
github:
  webhook_secret: psst
  auth_token: lol
registry:
  username: user
  password: pass
postgres:
  port: 5544
  database: littleblue
  username: littleblue
  password: cf713299cb2c4dc4b00adacb0ec01044
